language: php

php:
  - "7.2"

cache:
  directories:
    - $HOME/.cache/composer

install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - ./vendor/bin/phpunit --configuration ./phpunit.xml.dist